// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbRPfidFBinqF-t3u7sGsgepNAWb_stvA',
    appId: '1:186670410022:web:4a87a23685ec2f355239e7',
    messagingSenderId: '186670410022',
    projectId: 'cultureconnect-21b',
    authDomain: 'cultureconnect-21b.firebaseapp.com',
    storageBucket: 'cultureconnect-21b.firebasestorage.app',
    measurementId: 'G-M147YNY2EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlNjqdHUYzPNIC0UY18P6clVHJU5Qahc',
    appId: '1:186670410022:android:f54662147b64964d5239e7',
    messagingSenderId: '186670410022',
    projectId: 'cultureconnect-21b',
    storageBucket: 'cultureconnect-21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw1DhRSP7oPIJ7MLLfRphB1Yrvn9YXGm4',
    appId: '1:186670410022:ios:c73f3ad41f7fce265239e7',
    messagingSenderId: '186670410022',
    projectId: 'cultureconnect-21b',
    storageBucket: 'cultureconnect-21b.firebasestorage.app',
    iosClientId: '186670410022-7nv4uh48fb5lmql4j3ecqm4tn8qdgfgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultureConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw1DhRSP7oPIJ7MLLfRphB1Yrvn9YXGm4',
    appId: '1:186670410022:ios:c73f3ad41f7fce265239e7',
    messagingSenderId: '186670410022',
    projectId: 'cultureconnect-21b',
    storageBucket: 'cultureconnect-21b.firebasestorage.app',
    iosClientId: '186670410022-7nv4uh48fb5lmql4j3ecqm4tn8qdgfgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cultureConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbRPfidFBinqF-t3u7sGsgepNAWb_stvA',
    appId: '1:186670410022:web:2af163d90905e8de5239e7',
    messagingSenderId: '186670410022',
    projectId: 'cultureconnect-21b',
    authDomain: 'cultureconnect-21b.firebaseapp.com',
    storageBucket: 'cultureconnect-21b.firebasestorage.app',
    measurementId: 'G-DRKBSP45R9',
  );
}
